Repository microsoft/AirSim, pull requests merged in 2021-05, with the labels that each got.

#3680 Fix bugs in px4 .ulg viewing, and make tooltip avoid the closebox
  LogViewer/LogViewer/Controls/SimpleLineChart.xaml
  LogViewer/LogViewer/Controls/SimpleLineChart.xaml.cs
  LogViewer/LogViewer/LogViewer.csproj
  LogViewer/LogViewer/MainWindow.xaml.cs
  LogViewer/LogViewer/Model/Px4ULog.cs
Labels: px4

#3693 fix "ControlPortLocal"
  docs/px4_sitl.md
  docs/px4_sitl_wsl2.md
Labels: doc update

#3278 Update Camera FoV as well when using simSetCameraFoV API
  PythonClient/computer_vision/fov_change.py
  Unreal/Plugins/AirSim/Source/PIPCamera.cpp
Labels: api, bug

#2937 [Unity] Fix Car API
  Unity/AirLibWrapper/AirsimWrapper/Source/UnityImageCapture.cpp
  Unity/AirLibWrapper/AirsimWrapper/Source/Vehicles/Car/CarPawnApi.cpp
  Unity/AirLibWrapper/AirsimWrapper/Source/Vehicles/Car/CarPawnApi.h
  Unity/AirLibWrapper/AirsimWrapper/Source/Vehicles/Car/CarPawnSimApi.cpp
  Unity/AirLibWrapper/AirsimWrapper/Source/Vehicles/Car/CarPawnSimApi.h
  Unity/AirLibWrapper/AirsimWrapper/Source/Vehicles/Car/SimModeCar.cpp
  Unity/AirLibWrapper/AirsimWrapper/Source/Vehicles/Multirotor/FlyingPawn.cpp
  Unity/AirLibWrapper/AirsimWrapper/Source/Vehicles/Multirotor/MultirotorPawnSimApi.cpp
  Unity/AirLibWrapper/AirsimWrapper/Source/WorldSimApi.h
Labels: bug

#3730 Update who_is_using.md
  docs/who_is_using.md
Labels: doc update

#3656 ArduPilot: Reduce data copying, stack memory usage
  AirLib/include/vehicles/car/firmwares/ardurover/ArduRoverApi.hpp
  AirLib/include/vehicles/multirotor/firmwares/arducopter/ArduCopterApi.hpp
Labels: performance

#3697 Docs: Update use_precompiled.md
  docs/use_precompiled.md
Labels: doc update

#3699 Make falling leaves visible in depth and segmentation
  Unreal/Plugins/AirSim/Content/Weather/WeatherFX/Materials/M_Leaf_master.uasset
  Unreal/Plugins/AirSim/Content/Weather/WeatherFX/WeatherActor.uasset
Labels: feature request

#3705 Fix incorrect parsing of CameraDirector settings
  AirLib/include/common/AirSimSettings.hpp
Labels: bug

#3726 Use default sensors for default vehicle
  AirLib/include/common/AirSimSettings.hpp
Labels: bug

#3420 Improve spelling in simple_flight.md
  docs/simple_flight.md
Labels: doc update
