Repository microsoft/AirSim, pull requests merged in 2021-06, with the labels that each got.

#2936 Add API for list of vehicle names
  AirLib/include/api/RpcLibClientBase.hpp
  AirLib/include/api/WorldSimApiBase.hpp
  AirLib/include/common/common_utils/UniqueValueMap.hpp
  AirLib/src/api/RpcLibClientBase.cpp
  AirLib/src/api/RpcLibServerBase.cpp
  PythonClient/airsim/client.py
  Unity/AirLibWrapper/AirsimWrapper/Source/WorldSimApi.cpp
  Unity/AirLibWrapper/AirsimWrapper/Source/WorldSimApi.h
  Unreal/Plugins/AirSim/Source/WorldSimApi.cpp
  Unreal/Plugins/AirSim/Source/WorldSimApi.h
  docs/multi_vehicle.md
Labels: api, feature request

#3341 Fixed crash when calling simLoadLevel
  PythonClient/airsim/client.py
  Unreal/Plugins/AirSim/Source/SimMode/SimModeBase.cpp
Labels: api, bug, unreal-engine

#3436 Check for settings.json in current directory as well
  Unreal/Plugins/AirSim/Source/SimHUD/SimHUD.cpp
  Unreal/Plugins/AirSim/Source/SimHUD/SimHUD.h
  docs/settings.md
Labels: bug

#3755 PythonClient: Add __version__ attribute and use it to indicate version
  PythonClient/airsim/__init__.py
  PythonClient/docs/conf.py
  PythonClient/setup.py
Labels: feature request

#3100 [RFC] linux: llvm: specify llvm lib dir
  cmake/cmake-modules/CommonSetup.cmake
Labels: build

#3754 GazeboDrone project added to connect a gazebo drone to the AirSim drone
  GazeboDrone/CMakeLists.txt
  GazeboDrone/README.md
  GazeboDrone/src/main.cpp
Labels: feature request

#3472 Add object detection capability and python API
  AirLib/include/api/RpcLibAdaptorsBase.hpp
  AirLib/include/api/RpcLibClientBase.hpp
  AirLib/include/api/VehicleSimApiBase.hpp
  AirLib/include/common/CommonStructs.hpp
  AirLib/src/api/RpcLibClientBase.cpp
  AirLib/src/api/RpcLibServerBase.cpp
  HelloDrone/main.cpp
  PythonClient/airsim/client.py
  PythonClient/airsim/types.py
  PythonClient/detection/detection.py
  PythonClient/detection/setup_path.py
  Unity/AirLibWrapper/AirsimWrapper/Source/PawnSimApi.cpp
  Unity/AirLibWrapper/AirsimWrapper/Source/PawnSimApi.h
  Unreal/Plugins/AirSim/Content/Blueprints/BP_PIPCamera.uasset
  Unreal/Plugins/AirSim/Source/AirBlueprintLib.cpp
  Unreal/Plugins/AirSim/Source/AirBlueprintLib.h
  Unreal/Plugins/AirSim/Source/DetectionComponent.cpp
  Unreal/Plugins/AirSim/Source/DetectionComponent.h
  Unreal/Plugins/AirSim/Source/ObjectFilter.cpp
  Unreal/Plugins/AirSim/Source/ObjectFilter.h
  Unreal/Plugins/AirSim/Source/PIPCamera.cpp
  Unreal/Plugins/AirSim/Source/PIPCamera.h
  Unreal/Plugins/AirSim/Source/PawnSimApi.cpp
  Unreal/Plugins/AirSim/Source/PawnSimApi.h
Labels: feature request

#1938 Support for sim line-of-sight tests via RPC
  AirLib/include/api/RpcLibClientBase.hpp
  AirLib/include/api/VehicleSimApiBase.hpp
  AirLib/include/common/AirSimSettings.hpp
  AirLib/src/api/RpcLibClientBase.cpp
  AirLib/src/api/RpcLibServerBase.cpp
  Unity/AirLibWrapper/AirsimWrapper/Source/PawnSimApi.cpp
  Unity/AirLibWrapper/AirsimWrapper/Source/PawnSimApi.h
  Unreal/Plugins/AirSim/Source/PawnSimApi.cpp
  Unreal/Plugins/AirSim/Source/PawnSimApi.h
  docs/apis.md
Labels: feature request

#3653 Added Octo X config
  AirLib/include/vehicles/multirotor/MultiRotorParams.hpp
  AirLib/include/vehicles/multirotor/firmwares/mavlink/Px4MultiRotorParams.hpp
Labels: custom-model, feature request

#3785 Docs: Update minimum UE4 version to 4.25
  docs/build_linux.md
  docs/build_windows.md
  docs/unreal_custenv.md
Labels: doc update

#3611 Improve contributing docs
  docs/adding_new_apis.md
  docs/apis.md
  docs/code_structure.md
  mkdocs.yml
Labels: doc update

#3801 change sign of gravity in IMU
  AirLib/include/sensors/imu/ImuSimple.hpp
Labels: bug, sensors

#3757 Fix bug in UDP socket failing with WSAECONNRESET in the read thread
  AirLib/include/vehicles/multirotor/firmwares/mavlink/MavLinkMultirotorApi.hpp
  MavLinkCom/src/serial_com/UdpClientPort.cpp
  MavLinkCom/src/serial_com/UdpClientPort.hpp
  PythonClient/multirotor/opencv_show.py
Labels: bug, px4

#3788 Add detection support for all image types
  Unreal/Plugins/AirSim/Content/Blueprints/BP_PIPCamera.uasset
  Unreal/Plugins/AirSim/Source/AirBlueprintLib.h
  Unreal/Plugins/AirSim/Source/PIPCamera.cpp
Labels: feature request

#3784 add wrapper for line of sight APIs
  AirLib/include/api/RpcLibClientBase.hpp
  AirLib/include/api/VehicleSimApiBase.hpp
  AirLib/src/api/RpcLibClientBase.cpp
  AirLib/src/api/RpcLibServerBase.cpp
  PythonClient/airsim/client.py
  PythonClient/multirotor/line_of_sight.py
  Unity/AirLibWrapper/AirsimWrapper/Source/PawnSimApi.cpp
  Unity/AirLibWrapper/AirsimWrapper/Source/PawnSimApi.h
  Unreal/Plugins/AirSim/Source/PawnSimApi.cpp
  Unreal/Plugins/AirSim/Source/PawnSimApi.h
  docs/apis.md
Labels: api

#3789 Add object detection documentation
  docs/images/detection_python.png
  docs/images/detection_ue4.png
  docs/object_detection.md
  mkdocs.yml
Labels: doc update

#3305 Fixed issue where no new scene is rendered after simContinueForTime
  Unreal/Plugins/AirSim/Source/SimMode/SimModeWorldBase.cpp
  Unreal/Plugins/AirSim/Source/SimMode/SimModeWorldBase.h
Labels: api, bug, unreal-engine
