Repository microsoft/AirSim, pull requests merged in 2021-08, with the labels that each got.

#3914 Pr/changing gazebodrone build
  GazeboDrone/CMakeLists.txt
  GazeboDrone/README.md
  build.sh
  docs/gazebo_drone.md
  mkdocs.yml
Labels: doc update

#3937 Fix compression bug in segmentation palette
  Unreal/Plugins/AirSim/Content/HUDAssets/SegmentationMaterial.uasset
  Unreal/Plugins/AirSim/Content/HUDAssets/seg_color_palette.png
  Unreal/Plugins/AirSim/Content/HUDAssets/seg_color_palette.uasset
Labels: bug, images

#3876 Removed Custom Report Calls for Sim
  Unreal/Plugins/AirSim/Source/SimMode/SimModeBase.cpp
  Unreal/Plugins/AirSim/Source/Vehicles/Car/CarPawnSimApi.cpp
  Unreal/Plugins/AirSim/Source/Vehicles/Car/CarPawnSimApi.h
Labels: bug, feature request

#3907 Fix DepthPlanar capture
  Unreal/Plugins/AirSim/Content/Blueprints/BP_PIPCamera.uasset
Labels: bug, images

#3958 Sai webinar added to tutorial list
  README.md
Labels: doc update

#2942 Update Docker scripts, info
  docker/Dockerfile_binary
  docker/Dockerfile_source
  docker/download_blocks_env_binary.sh
  docker/run_airsim_image_binary.sh
  docker/run_airsim_image_source.sh
  docs/docker_ubuntu.md
Labels: Docker

#3988 Update px4_multi_vehicle.md
  docs/px4_multi_vehicle.md
Labels: doc update
