Repository microsoft/AirSim, pull requests merged in 2021-12, with the labels that each got.

#3746 Added movetoGPS
  AirLib/include/common/EarthUtils.hpp
  AirLib/include/vehicles/multirotor/api/MultirotorApiBase.hpp
  AirLib/include/vehicles/multirotor/api/MultirotorRpcLibClient.hpp
  AirLib/src/vehicles/multirotor/api/MultirotorApiBase.cpp
  AirLib/src/vehicles/multirotor/api/MultirotorRpcLibClient.cpp
  AirLib/src/vehicles/multirotor/api/MultirotorRpcLibServer.cpp
  PythonClient/airsim/client.py
Labels: feature request

#3976 Add ROS2 wrapper
  .gitignore
  ros2/src/airsim_interfaces/CMakeLists.txt
  ros2/src/airsim_interfaces/msg/Altimeter.msg
  ros2/src/airsim_interfaces/msg/CarControls.msg
  ros2/src/airsim_interfaces/msg/CarState.msg
  ros2/src/airsim_interfaces/msg/Environment.msg
  ros2/src/airsim_interfaces/msg/GPSYaw.msg
  ros2/src/airsim_interfaces/msg/GimbalAngleEulerCmd.msg
  ros2/src/airsim_interfaces/msg/GimbalAngleQuatCmd.msg
  ros2/src/airsim_interfaces/msg/VelCmd.msg
  ros2/src/airsim_interfaces/msg/VelCmdGroup.msg
  ros2/src/airsim_interfaces/package.xml
  ros2/src/airsim_interfaces/srv/Land.srv
  ros2/src/airsim_interfaces/srv/LandGroup.srv
  ros2/src/airsim_interfaces/srv/Reset.srv
  ros2/src/airsim_interfaces/srv/SetGPSPosition.srv
  ros2/src/airsim_interfaces/srv/SetLocalPosition.srv
  ros2/src/airsim_interfaces/srv/Takeoff.srv
  ros2/src/airsim_interfaces/srv/TakeoffGroup.srv
  ros2/src/airsim_ros_pkgs/CMakeLists.txt
  ros2/src/airsim_ros_pkgs/README.md
  ros2/src/airsim_ros_pkgs/include/airsim_ros_wrapper.h
  ros2/src/airsim_ros_pkgs/include/airsim_settings_parser.h
  ros2/src/airsim_ros_pkgs/include/geodetic_conv.hpp
  ros2/src/airsim_ros_pkgs/include/math_common.h
  ros2/src/airsim_ros_pkgs/include/pd_position_controller_simple.h
  ros2/src/airsim_ros_pkgs/include/utils.h
  ros2/src/airsim_ros_pkgs/launch/airsim_node.launch.py
  ros2/src/airsim_ros_pkgs/launch/airsim_with_simple_PD_position_controller.launch.py
  ros2/src/airsim_ros_pkgs/launch/dynamic_constraints.launch.py
  ros2/src/airsim_ros_pkgs/launch/position_controller_simple.launch.py
  ros2/src/airsim_ros_pkgs/launch/rviz.launch.py
  ros2/src/airsim_ros_pkgs/launch/static_transforms.launch.py
  ros2/src/airsim_ros_pkgs/package.xml
  ros2/src/airsim_ros_pkgs/rviz/default.rviz
  ros2/src/airsim_ros_pkgs/scripts/car_joy
  ros2/src/airsim_ros_pkgs/src/airsim_node.cpp
  ros2/src/airsim_ros_pkgs/src/airsim_ros_wrapper.cpp
  ros2/src/airsim_ros_pkgs/src/airsim_settings_parser.cpp
  ros2/src/airsim_ros_pkgs/src/pd_position_controller_simple.cpp
  ros2/src/airsim_ros_pkgs/src/pd_position_controller_simple_node.cpp
  tools/Dockerfile-ROS2
Labels: ros

#3940 Add API to list all assets
  AirLib/include/api/RpcLibClientBase.hpp
  AirLib/include/api/WorldSimApiBase.hpp
  AirLib/src/api/RpcLibClientBase.cpp
  AirLib/src/api/RpcLibServerBase.cpp
  PythonClient/airsim/client.py
  PythonClient/environment/create_objects.py
  Unity/AirLibWrapper/AirsimWrapper/Source/WorldSimApi.cpp
  Unity/AirLibWrapper/AirsimWrapper/Source/WorldSimApi.h
  Unreal/Plugins/AirSim/Source/AirBlueprintLib.cpp
  Unreal/Plugins/AirSim/Source/WorldSimApi.cpp
  Unreal/Plugins/AirSim/Source/WorldSimApi.h
Labels: feature request

#4198 Update image_apis.md
  docs/image_apis.md
Labels: doc update

#4203 Fix simAddVehicle for Car vehicle
  PythonClient/car/runtime_car.py
  Unreal/Plugins/AirSim/Source/SimMode/SimModeBase.cpp
  Unreal/Plugins/AirSim/Source/SimMode/SimModeWorldBase.cpp
  docs/faq.md
  docs/images/HelloSpawnedDrones.gif
  docs/images/simAddVehicle_Car.gif
  docs/multi_vehicle.md
Labels: bug

#3949 Camera replaced by Cinematographic Camera (CinemAirSim)
  AirLib/include/api/RpcLibClientBase.hpp
  AirLib/include/api/WorldSimApiBase.hpp
  AirLib/src/api/RpcLibClientBase.cpp
  AirLib/src/api/RpcLibServerBase.cpp
  PythonClient/airsim/client.py
  Unity/AirLibWrapper/AirsimWrapper/Source/WorldSimApi.cpp
  Unity/AirLibWrapper/AirsimWrapper/Source/WorldSimApi.h
  Unreal/Plugins/AirSim/Source/AirSim.Build.cs
  Unreal/Plugins/AirSim/Source/PIPCamera.cpp
  Unreal/Plugins/AirSim/Source/PIPCamera.h
  Unreal/Plugins/AirSim/Source/WorldSimApi.cpp
  Unreal/Plugins/AirSim/Source/WorldSimApi.h
Labels: feature request
