Repository microsoft/AirSim, pull requests merged in 2022-06, with the labels that each got.

#4562 Snow and rain visible from capture images
  Unreal/Plugins/AirSim/Content/Weather/WeatherFX/Materials/M_RainDrop_Master.uasset
  Unreal/Plugins/AirSim/Content/Weather/WeatherFX/Materials/M_SnowFlake_Master.uasset
  Unreal/Plugins/AirSim/Content/Weather/WeatherFX/WeatherActor.uasset
Labels: bug, images

#4558 Fix settings FOV not applied
  Unreal/Plugins/AirSim/Source/PIPCamera.cpp
Labels: bug

#4551 Fix simLoadLevel and Levels OptionsMenu
  Unreal/Plugins/AirSim/Content/HUDAssets/OptionsMenu.uasset
  Unreal/Plugins/AirSim/Source/AirBlueprintLib.cpp
  Unreal/Plugins/AirSim/Source/AirBlueprintLib.h
  Unreal/Plugins/AirSim/Source/AirsimLevelStreaming.cpp
  Unreal/Plugins/AirSim/Source/AirsimLevelStreaming.h
  Unreal/Plugins/AirSim/Source/SimHUD/SimHUD.cpp
  Unreal/Plugins/AirSim/Source/WorldSimApi.cpp
  Unreal/Plugins/AirSim/Source/WorldSimApi.h
Labels: bug, unreal-engine
